POST http://localhost:5001/api/v1/extract
{
  "post_collection_id": "503cf2df-77ac-4b6d-ac52-6ba7181b92c8",
  "posts": [
    {
      "post_id": "111812360133921665", 
      "parent_post": null, 
      "url": "https://mastodon.social/@GottaLaff/111812360133921665", 
      "created_at": "2024-01-24T18:33:37.864000+00:00", 
      "account": {"account_id": "109253075745809751", "username": "GottaLaff", "created_at": "2022-10-29T00:00:00+00:00"}, 
      "hashtags": [], 
      "content": "You may disagree fervently with Pres. Biden's Israel policies, and that's fine. But if you come into my feed calling him \"Genocide Joe\" or any variation on that theme, you're blocked. I've already had to block a few accounts for this.Pres. Biden is not \"for genocide.\" I will not argue with you on this topic, nor do I discuss the Israel/Hamas war here. But I will not tolerate accusations of \"genocide\" by Pres. Biden. He's not \"pro genocide.\" If that's a prob, it's on you.",
      "edited": false, 
      "media_attachments": [], 
      "metrics": {"reposts_count": 39, "favourites_count": 77, "replies_count": 12}
    },
    {
      "post_id": "111812307009854713", 
      "parent_post": {
        "parent_post_id": "111812292986601531", 
        "parent_post_url": "https://mastodon.social/@gwynnion/111812292986601531"
      }, 
      "url": "https://mastodon.social/@gwynnion/111812307009854713", 
      "created_at": "2024-01-24T18:20:07.253000+00:00", 
      "account": {"account_id": "109836797527169643", "username": "gwynnion", "created_at": "2023-02-09T00:00:00+00:00"}, 
      "hashtags": [], 
      "content": "It's demoralizing to a lot of people to watch a Democratic president arm Israel to do ethnic cleansing in Gaza, shovel money toward cops after George Floyd and the biggest civil rights protests in recent memory, act surprised and confused when Roe is struck down with no plan to fight back, have a passive DOJ punting Trump's criminality onto state attorney generals, and be essentially AWOL as anti-trans legislation goes nationwide.", 
      "edited": false, 
      "media_attachments": [], 
      "metrics": {"reposts_count": 7, "favourites_count": 14, "replies_count": 1}
    },
    {
      "post_id": "111812205058034643",
      "parent_post": null,
      "url": "https://mastodon.scot/@russellt/111812205058034643",
      "created_at": "2024-01-24T17:54:11.592000+00:00",
      "account": {
          "account_id": "109300962355189432",
          "username": "russellt",
          "created_at": "2022-11-07T00:00:00+00:00"
      },
      "hashtags": [],
      "content": "Netanyahu's Likud party to hold conference to discuss building settlements in the Gaza Strip after the warThe conference, titled \u201cIsrael\u2019s Victory\u201d, is \"expected to be attended by thousands of Israelis from the religious & extreme nationalist movement, including 20 ministers & members of the Knesset.\"~Israeli newspaper Yedioth AhronothJan 24, 12.30 GMT AJ updateshttps://www.haaretz.com/israel-news/2024-0",
      "edited": false,
      "media_attachments": [],
      "metrics": {
          "reposts_count": 3,
          "favourites_count": 4,
          "replies_count": 2
      }
    },
    {
      "post_id": "111467074680989081",
      "url": "http://localhost:3000/@star16/111467074680989081",
      "created_at": "2023-11-24T19:02:59.974000+00:00",
      "account": {
        "account_id": "111467066903686717",
        "username": "star16",
        "created_at": "2023-11-24T00:00:00+00:00"
      },
      "hashtags": [],
      "content": "hello, reddit!",
      "edited": false,
      "parent_post": null,
      "media_attachments": [],
      "metrics": {
        "reposts_count": 19,
        "favourites_count": 0,
        "replies_count": 0
      }
    }
  ],
  "source": {
    "url": "http://localhost:3000",
    "source_type": "mastodon"
  },
  "created_at": "2023-11-25T16:20:23.751830",
  "trigger_timestamp": "2023-11-25T16:18:09.252144"
}
